version: '3.8'

services:
  db:
    image: postgres:12
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: